#!/usr/bin/env node
let json = require('format-json');
let program = require('commander');
let LaunchDarklyUtils = require('./dist/src/LaunchDarklyUtils.js').LaunchDarklyUtils;
require('dotenv').config();

if (!process.env.LAUNCHDARKLY_API_TOKEN) {
    console.log('missing environment var LAUNCHDARKLY_API_TOKEN - exiting..');
    process.exit(1);
}

let log = console;

// fallback to bunyan logger if debug mode
if (process.env.LAUNCHDARKLY_API_LOGLEVEL === 'debug') log = undefined;

process.on('unhandledRejection', (reason, p) => {
    console.error(json.plain({ error: reason }));
    process.exit(1);
});

new LaunchDarklyUtils().create(process.env.LAUNCHDARKLY_API_TOKEN, log).then(function(ldUtils) {
    program.version('1.0.0').description('Manage LaunchDarkly flags and other assets from the command line.');

    program
        .command('getFeatureFlags <projectKey>')
        .description('get all flags for a given project')
        .action(function(projectKey) {
            ldUtils.flags.getFeatureFlags(projectKey).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command(`getFeatureFlag <projectKey> <featureFlagKey> [environmentKeyQuery]`)
        .description('get a single flag - with optional env')
        .action(function(projectKey, featureFlagKey, environmentKeyQuery) {
            ldUtils.flags.getFeatureFlag(projectKey, featureFlagKey, environmentKeyQuery).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command(`getFeatureFlagState <projectKey> <featureFlagKey> <environmentKeyQuery>`)
        .description('get boolean flag state')
        .action(function(projectKey, featureFlagKey, environmentKeyQuery) {
            ldUtils.flags.getFeatureFlagState(projectKey, featureFlagKey, environmentKeyQuery).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command(`toggleFeatureFlag <projectKey> <featureFlagKey> <environmentKeyQuery> <value>`)
        .description('set boolean flag state')
        .action(function(projectKey, featureFlagKey, environmentKeyQuery, value) {
            let enabled = value === 'true';
            ldUtils.flags
                .toggleFeatureFlag(projectKey, featureFlagKey, environmentKeyQuery, enabled)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command(`migrateFeatureFlag <projectKey> <featureFlagKey> <fromEnv> <toEnv> (includeState)`)
        .description('migrate flag settings from one environment to another')
        .action(function(projectKey, featureFlagKey, fromEnv, toEnv, includeState) {
            ldUtils.flags
                .migrateFeatureFlag(projectKey, featureFlagKey, fromEnv, toEnv, includeState)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command(`bulkMigrateFeatureFlags <projectKey> <featureFlagKeys> <fromEnv> <toEnv> (includeState)`)
        .description('migrate multiple flag settings from one environment to another')
        .action(function(projectKey, featureFlagKeys, fromEnv, toEnv, includeState) {
            ldUtils.flags
                .bulkMigrateFeatureFlags(projectKey, featureFlagKeys, fromEnv, toEnv, includeState)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command(`restoreFeatureFlags <projectKey> <featureFlagKeys> <targetEnv> <backupJsonFile> (includeState)`)
        .description('restore environment flag settings from a backup file - backup from getFeatureFlags')
        .action(function(projectKey, featureFlagKeys, targetEnv, backupJsonFile, includeState) {
            ldUtils.flags
                .restoreFeatureFlags(projectKey, featureFlagKeys, targetEnv, backupJsonFile, includeState)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command('getCustomRoles')
        .description('get all custom roles in account')
        .action(function() {
            ldUtils.roles.getCustomRoles().then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getCustomRole <customRoleKey>')
        .description('get custom role by key')
        .action(function(customRoleKey) {
            ldUtils.roles.getCustomRole(customRoleKey).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getCustomRoleById <customRoleId>')
        .description('get custom role by id')
        .action(function(customRoleId) {
            ldUtils.roles.getCustomRoleById(customRoleId).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command(`createCustomRole <customRoleKey> <customRoleName> <customRolePolicyArray> [customRoleDescription]`)
        .description('create custom role')
        .action(function(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription) {
            customRolePolicyArray = JSON.parse(customRolePolicyArray);
            ldUtils.roles
                .createCustomRole(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command(`updateCustomRole <customRoleKey> <customRoleName> <customRolePolicyArray> [customRoleDescription]`)
        .description('update custom role')
        .action(function(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription) {
            customRolePolicyArray = JSON.parse(customRolePolicyArray);
            ldUtils.roles
                .updateCustomRole(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command(`upsertCustomRole <customRoleKey> <customRoleName> <customRolePolicyArray> [customRoleDescription]`)
        .description('create or update custom role')
        .action(function(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription) {
            customRolePolicyArray = JSON.parse(customRolePolicyArray);
            ldUtils.roles
                .upsertCustomRole(customRoleKey, customRoleName, customRolePolicyArray, customRoleDescription)
                .then(function(response) {
                    console.log(json.plain(response));
                });
        });

    program
        .command('bulkUpsertCustomRoles <roleBulkLoadFile>')
        .description('path to a file containing array of role json')
        .action(function(roleBulkLoadFile) {
            ldUtils.roles.bulkUpsertCustomRoles(roleBulkLoadFile).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('bulkUpsertCustomRoleFolder <roleFolder>')
        .description('path to a directory containing multiple files of role json')
        .action(function(roleFolder) {
            ldUtils.roles.bulkUpsertCustomRoleFolder(roleFolder).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('inviteTeamMember <emailAddress> <initialRoleName>')
        .description('Invite a New Team Member')
        .action(function(emailAddress, initialRoleName) {
            ldUtils.members.inviteTeamMember(emailAddress, initialRoleName).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getTeamMembers')
        .description('list all team members in account')
        .action(function() {
            ldUtils.members.getTeamMembers().then(function(response) {
                console.log(json.plain(response));
            });
        });
    
    program
        .command('getPendingTeamMembers')
        .description('List all Pending Team Members in Account')
        .action(function() {
            ldUtils.members.getPendingTeamMembers().then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getTeamMember <memberId>')
        .description('get a team member by id')
        .action(function(memberId) {
            ldUtils.members.getTeamMember(memberId).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getTeamMemberByEmail <emailAddress>')
        .description('get a team member by email address')
        .action(function(emailAddress) {
            ldUtils.members.getTeamMemberByEmail(emailAddress).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('deleteTeamMember <memberId>')
        .description('Delete a Team Member by ID')
        .action(function(memberId) {
            ldUtils.members.deleteTeamMember(memberId).then(function(response) {
                console.log(response ? "User Deleted" : "User Deletion Failed");
            });
        });

    program
        .command('deletePendingTeamMembers')
        .description('Delete all Pending Team Members')
        .action(function() {
            ldUtils.members.deletePendingTeamMembers().then(function(response) {
                console.log(json.plain(response));
            });
        });

    program
        .command('getTeamMemberCustomRoles <emailAddress>')
        .description('get a team members custom roles by email address')
        .action(function(emailAddress) {
            ldUtils.members.getTeamMemberCustomRoles(emailAddress).then(function(response) {
                console.log(json.plain(response));
            });
        });

    program.on('--help', function() {
        console.log('\n  See https://github.com/zotoio/launchdarkly-nodeutils/API.md for examples.\n');
    });

    if (process.argv.length < 3) {
        program.help();
        process.exit(1);
    }

    program.parse(process.argv);
});
